name: Test Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build all actions
      run: |
        apt install -qy yamllint
        which yamllint

        for action in actions/*; do
          if [[ ! -d "$action" ]]; then
            continue
          fi
          echo "====> Linting $action"
          pushd "$action" >/dev/null
          docker build -t "test-$action" .
          popd >/dev/null
        done
