name: Test Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Installing yamllint
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt install -qy yamllint >/dev/null

    - name: Build all actions
      run: |
        for action in actions/*; do
          if [[ ! -d "$action" ]]; then
            continue
          fi

          echo "====> Linting $action"
          pushd "$action" >/dev/null
          docker build -qt "test-$action" . || {
            echo "!     Failed to build $action"
            exit 1
          }

          yamllint . || {
            echo "!     Failed to lint $action"
            exit 1
          }
          popd >/dev/null
        done
