name: Test Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build all actions
      run: |
        pushd .github/actions >/dev/null
        for f in *; do
          if [ -d "$f" ]; then
            echo "$f"
          fi
        done
