name: Test Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build all actions
      run: |
        for f in actions; do
          if [[ ! -d "$f" ]]; then
            continue
          fi
          echo "actions/$f"
        done
